### PR TITLE
Update Undude.kt

### PR DESCRIPTION
**Pull request by dotdashnotdot**
1) The stack is taking care of maintaining a reference of ret & undo for you, so reckon you don't need the list.
2) Think the error handling could be a bit better (Java's lack of AggregateException is something new I learned tonight!)
3) Ditched the Undoable because I couldn't see much of a use case for it.

Neat little project though 👍

### CODE REVIEW

**Comment by dotdashnotdot** [comment]
FYI, don't expect this to be merged, just adding some thoughts as requested :)

**Comment by spaoletti** [comment]
>     1. The stack is taking care of maintaining a reference of ret & undo for you, so reckon you don't need the list.

What stack? You are just undoing one action, it seems. The last one. All the previous successful operations are lost, and cannot be undone anymore

>     2. Think the error handling could be a bit better (Java's lack of AggregateException is something new I learned tonight!)

Yeah definitely. Very raw error handling.

>     3. Ditched the Undoable because I couldn't see much of a use case for it.

I wrote a use case in the readme, i have to assume it's not clear enough... You can use Undoable if you want to pass around "Undoable actions". So, for example, if you want to have a method that returns the action AND the undo of that action

**Review by spaoletti — COMMENTED** [review]
https://github.com/spaoletti/undude/pull/1#issuecomment-865916573

**Comment by dotdashnotdot** [comment]
> > ```
> > 1. The stack is taking care of maintaining a reference of ret & undo for you, so reckon you don't need the list.
> > ```
> 
> What stack? You are just undoing one action, it seems. The last one. All the previous successful operations are lost, and cannot be undone anymore
> 
> > ```
> > 2. Think the error handling could be a bit better (Java's lack of AggregateException is something new I learned tonight!)
> > ```
> 
> Yeah definitely. Very raw error handling.
> 
> > ```
> > 3. Ditched the Undoable because I couldn't see much of a use case for it.
> > ```
> 
> I wrote a use case in the readme, i have to assume it's not clear enough... You can use Undoable if you want to pass around "Undoable actions". So, for example, if you want to have a method that returns the action AND the undo of that action

The code appears to pretty much be pass in two callables. If the first one throws an exception, call the second. To add more transactions, you keep calling more & more. This appends stack frames to the stack with each method called. The variable is being maintained for you in each previous stack frame. (Think how recursive functions work)

```
fun sumBinaryTree(node: Node): int {
    if(node == null) {
        return 0
    }

    if(!node.HasChildren) {
        return node.Value
    }

    var leftSum = sumBinaryTree(node.LeftChild)
    var rightSum = leftSum + sumBinaryTree(node.RightChild)
    return leftSum + rightSum;
}
```

**Pull request closed without merging**
